# Generated by Django 4.2.1 on 2023-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
