# Generated by Django 4.2.1 on 2023-05-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("description", models.CharField(max_length=1000, verbose_name="Descriação")),
                ("duration", models.PositiveIntegerField(verbose_name="Duração em sengundo")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="core.project"
                    ),
                ),
            ],
            options={
                "ordering": ("description",),
            },
        ),
    ]
